# Generated by Django 3.2.9 on 2022-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_patients_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='state',
            field=models.CharField(default='Not consulted', max_length=9999999999),
        ),
    ]
