# Generated by Django 3.2.9 on 2022-03-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_appointments_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
    ]
