# Generated by Django 3.2.9 on 2022-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_remove_payments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmotif',
            name='validity',
            field=models.IntegerField(default=0, max_length=999),
            preserve_default=False,
        ),
    ]
