# Generated by Django 3.2.9 on 2022-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_payments_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
