# Generated by Django 3.2.9 on 2022-03-09 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_payments_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateField(default=datetime.date(2022, 3, 9)),
        ),
    ]
