# Generated by Django 3.2.9 on 2022-03-09 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_payments_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmotif',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 12, 21, 51, 116011)),
        ),
    ]
