# Generated by Django 3.2.9 on 2022-06-01 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20220601_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.admins'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 11, 15, 57, 508052)),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
