# Generated by Django 3.2.9 on 2022-06-01 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20220601_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.admins'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.admins'),
        ),
        migrations.AddField(
            model_name='principalreceptionist',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.admins'),
        ),
        migrations.AddField(
            model_name='servicereceptionist',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.admins'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 12, 46, 23, 54422)),
        ),
    ]
