# Generated by Django 3.2.9 on 2022-06-02 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20220601_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='has_paid',
        ),
        migrations.AddField(
            model_name='patientdepartments',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 13, 35, 873093)),
        ),
    ]
