# Generated by Django 3.2.9 on 2022-06-11 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20220602_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmotif',
            old_name='durée_en_jours',
            new_name='duree_en_jours',
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 11, 7, 56, 722357)),
        ),
    ]
