# Generated by Django 3.2.9 on 2022-06-11 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20220611_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmotif',
            name='validity',
        ),
        migrations.AlterField(
            model_name='paymentmotif',
            name='amount_motif',
            field=models.CharField(max_length=9999999999),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 11, 32, 2, 680854)),
        ),
    ]
