# Generated by Django 3.2.9 on 2022-06-12 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_auto_20220611_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmotif',
            name='payment_motif',
            field=models.CharField(max_length=9999999999),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 11, 22, 26, 390386)),
        ),
    ]
