# Generated by Django 3.2.9 on 2022-06-12 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_auto_20220612_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.departments'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 12, 45, 11, 309678)),
        ),
    ]
