# Generated by Django 3.2.9 on 2022-06-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_auto_20220612_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 12, 52, 39, 104139)),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug_prescription',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='examinations',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='recommendations',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
    ]
