# Generated by Django 3.2.9 on 2022-06-12 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_auto_20220612_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 12, 58, 23, 188696)),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.departments'),
            preserve_default=False,
        ),
    ]
