# Generated by Django 3.2.9 on 2022-06-16 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_auto_20220612_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmotif',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 6, 20, 58, 173401)),
        ),
        migrations.AlterField(
            model_name='principalreceptionist',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicereceptionist',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
