# Generated by Django 3.2.9 on 2022-06-16 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_auto_20220616_0633'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='payments',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 7, 6, 19, 593267)),
        ),
    ]
