# Generated by Django 3.2.9 on 2022-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_auto_20220616_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmotif',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='validity',
        ),
        migrations.AddField(
            model_name='payments',
            name='valid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
