# Generated by Django 3.2.9 on 2022-06-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_paymentmotif_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmotif',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 9, 10, 11, 971724)),
        ),
    ]
